import "./globals.css";
import AuthSessionProvider from "@/components/AuthSessionProvider";

export const metadata = {
  title: "Ledger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthSessionProvider>
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
