# .github/workflows/poll-emails.yml
name: Poll Emails

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes UTC (shortest allowed interval). :contentReference[oaicite:0]{index=0}
  workflow_dispatch: {}  # manual trigger

concurrency:
  group: poll-emails
  cancel-in-progress: false

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call the email poller endpoint
        run: |
          echo "Calling email poller..."
          status=$(curl -sS -o /dev/null -w "%{http_code}" https://ledger-4u4h.vercel.app/api/cron/process)
          echo "Endpoint responded with status $status"
          if [ "$status" != "200" ]; then
            echo "❌ Email polling failed with status $status"
            exit 1
          fi
          echo "✅ Email polling completed successfully"